name_project: moon-terminal-example
description: Moon Terminal Example
build_dir: build
name_build: moon-terminal-example
build_system_exe: make
c_compiler: gcc-11
cxx_compiler: g++-11
build_system: Unix Makefiles
cmake_flags: []
build_system_flags: []